### ISSUE TITLE
Enabling performance counters in Moca

### ISSUE THREAD

**Issue by NomeeHilton** [ucb-bar/MoCA#1]
I want to enable the performance counters to track some metrics in the gemmini accelerators like the cache hit/miss etc. I realized that in order to enable the performance counters, I have to add "WithAutoCounter" in the configuration and regenerate the bitstream for that configuration. I tried doing that but unfortunately with eight cores and gemmini accelerator attached, my bitstream generation fails in the middle with this error:
<img width="1185" alt="Screenshot 2023-03-08 at 8 51 55 PM" src="https://user-images.githubusercontent.com/127266253/223895261-e47704d5-6bdc-42e8-aec0-1c14f2443e54.png">

Seems like the design is too large for the FPGA used (using aws ec2 instance). How did u generate the bitstream for ur design and enabled ur design with 8 cores to fit in the Fpga provided by the aws ec2 f1 instance?

**Comment by SeahK** [comment]
Could you use "MOCAGemminiConfig" config for Gemmini?
We used GemminiConfigs.dummyConfig to fit 8 cores.
